config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'trackers#index'
  resources :users, only: %i[new create]
  # resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :trackers do
    resources :grades
    resources :entries
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Superclass for all models in the application
#
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_address.rb
# frozen_string_literal: true

# Stores user email addresses
#
class EmailAddress < ApplicationRecord

  belongs_to :user

  validates :email_address, 'valid_email_2/email': { mx: true, disposable: true }
  validates :email_address, uniqueness: true
  validates :verified_at, allow_nil: true, date: true
  validates :default, uniqueness: { scope: :user }, if: :default?

  scope :default, -> { where(default: true) }
  scope :verified, -> { where.not(verified_at: nil) }
  scope :unverified, -> { where(verified_at: nil) }

end

app/models/entry.rb
# frozen_string_literal: true

# A single tracker entry on a specific date
#
class Entry < ApplicationRecord

  belongs_to :tracker
  belongs_to :grade

  validates :date, date: true, uniqueness: { scope: :tracker }

end

app/models/grade.rb
# frozen_string_literal: true

# A level of achievement for a tracker
#
class Grade < ApplicationRecord

  ALLOWED_COLORS = %w[
    red orange yellow olive green teal blue violet purple pink brown grey black
  ].freeze

  belongs_to :tracker

  has_many :entries

  validates :label, length: { minimum: 1, maximum: 16 }
  validates :color, inclusion: { in: ALLOWED_COLORS }

end

app/models/tracker.rb
# frozen_string_literal: true

# A single category of journal entries for a user
#
class Tracker < ApplicationRecord

  belongs_to :user

  has_many :entries
  has_many :grades

  validates :name, presence: true, length: { minimum: 2, maximum: 255 }
  validates :name, uniqueness: { scope: :user }

end

app/models/user.rb
# frozen_string_literal: true

# Users of the application
#
class User < ApplicationRecord

  has_secure_password

  validates :name, presence: true, length: { minimum: 2, maximum: 255 }

  has_many :trackers
  has_many :email_addresses

  has_one :email_address, -> { default }

end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Superclass for all controllers in the application
#
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

# Handles operations for adding entries to trackers
#
class EntriesController < ApplicationController
end

app/controllers/grades_controller.rb
# frozen_string_literal: true

# Manages the different grades that can be assigned to entries in a tracker
#
class GradesController < ApplicationController

  before_action do
    @tracker = current_user.trackers.find(params[:tracker_id])
    @grade = @tracker.grades.find(params[:id]) if params[:id]
  end

  def index; end

  def new
    @grade = @tracker.grades.new
  end

  def create
    @grade = @tracker.grades.new(grade_params)
    if @grade.save
      redirect_to grades_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @grade.update_attributes(grade_params)
      redirect_to grades_path
    else
      render :edit
    end
  end

  def destroy
    flash[:errors] = @grade.errors unless @grade.destroy
    redirect_to grades_path
  end

end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Handles user sessions - login and logout
#
class SessionsController < ApplicationController

  layout 'narrow'

  before_action only: %i[new create] do

  end

  def new
    @login_form = LoginForm.new
    render 'forms/simple_login_form'
  end

  def create
    @login_form = LoginForm.new(login_params)
    # if @login_form.validate

    if @login_form.valid?
      session[:current_user] = @login_form.authenticated_user
      redirect_to trackers_path
    else
      puts @login_form.inspect
      render 'forms/simple_login_form', status: 401
    end

    # @user = User.authenticate(params[:email_address], params[:password])
    # if @user
    #   session[:current_user] = @user
    #   redirect_to trackers_path
    # else
    #   render :new
    # end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path
  end

  private

  def login_params
    params.require(:login_form).permit(:email_address, :password)
  end

end

app/controllers/trackers_controller.rb
# frozen_string_literal: true

# Manages trackers created by users
#
class TrackersController < ApplicationController

  before_action do
    @tracker = current_user.trackers.find(params[:id]) if params[:id]
  end

  def index
    @trackers = [] # current_user.trackers
  end

  def show; end

  def new
    @tracker = current_user.trackers.new
  end

  def create
    @tracker = current_user.trackers.new(tracker_params)
    if @tracker.save
      render :new
    else
      redirect_to trackers_path
    end
  end

  def edit; end

  def update
    if @tracker.update(tracker_params)
      redirect_to trackers_path
    else
      render :edit
    end
  end

  def destroy
    flash[:errors] = @tracker.errors unless @tracker.destroy
    redirect_to trackers_path
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Allows users to sign up and manage their accounts
#
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user] = @user
      redirect_to trackers_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application-wide view helpers
#
module ApplicationHelper

  def field_errors(errors)
    return unless errors
    tag.small class: 'form-text text-danger' do
      errors.join(', ').humanize
    end
  end

  # From https://github.com/rwz/nestive/blob/master/lib/nestive/layout_helper.rb
  def extends(layout, &block)
    # Make sure it's a string
    layout = layout.to_s

    # If there's no directory component, presume a plain layout name
    layout = "layouts/#{layout}" unless layout.include?('/')

    # Capture the content to be placed inside the extended layout
    @view_flow.get(:layout).replace capture(&block)

    render file: layout
  end

end

app/views/application/_assets.html.erb
<script src="https://kit.fontawesome.com/0f1fcc12a3.js" crossorigin="anonymous"></script>
<script src="js/form_validator.js" defer></script>

app/views/application/_bootstrap_css.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.4.1/cosmo/bootstrap.min.css" integrity="sha256-KgiMiZgZazlcRqcTnpKlQRyoi1Y79W1dsn5CtKFtwH0=" crossorigin="anonymous" />

app/views/application/_bootstrap_js.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-tokenfield@0.12.0/dist/bootstrap-tokenfield.min.js" integrity="sha256-jdwX0QzXB7z7Xc7Vz0ovtIHWO5qIZWg0aLcGv44JDgE=" crossorigin="anonymous"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

app/views/application/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p>Copyright &copy; 2020 - Intrabase Solutions Ltd.</p>
  </div>
</footer>

app/views/application/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fas fs-white fa-address-book d-inline-block align-absmiddle"></i>
        Habit Tracker
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>

        </ul>
        
        <ul class="navbar-nav my-2 my-md-0">
          <% if false %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdown07">
                <a class="dropdown-item" href="#">My Account</a>
                <a class="dropdown-item" href="#">Sign Out</a>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="#">Sign In</a>
            </li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>
</header>

app/views/forms/login_form.html.erb
<%= form_with model: @login_form, url: login_path do |form|%>

  <% if @login_form.errors %>
    <div class="alert alert-danger">
      <% if @login_form.errors[:base].present? %>
        <%= @login_form.errors[:base].join(', ').humanize %>
      <% else %>
        Please correct the errors below and try again
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email_address %>
    <%= form.email_field :email_address, class: @login_form.class_for(:email_address), required: true %>
    <%= field_errors(@login_form.errors_for(:email_address)) %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: @login_form.class_for(:password), required: true %>
    <%= field_errors(@login_form.errors_for(:password)) %>
  </div>
  <%= form.submit 'Sign In', class: 'btn btn-primary' %>

<% end %>

app/views/forms/simple_login_form.html.erb
<%= simple_form_for @login_form, method: :post, url: login_path, wrapper: :vertical_form do |f| %>
  <%= f.error_notification %>
  <%= f.input :email_address, required: true, input_html: { autocomplete: 'email' } %>
  <%= f.input :password, required: true, input_html: { autocomplete: 'current-password' } %>
  <%= f.button :submit, 'Log in', class: "btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habits</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render "application/bootstrap_css" %>
    <%= render "application/assets" %>
  </head>

  <body class="bg-light">
    <%= render 'application/header' %>
    <main role="main">
      <%= yield %>
    </main>
    <%= render 'application/footer' %>
    <%= render 'application/bootstrap_js' %>
  </body>
</html>

app/views/layouts/narrow.html.erb
<%= extends :application do %>
  
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <% if @page_title %>
          <h1>@page_title</h1>
        <% end %>
        <%= yield %>
      </div>
      <div class="col-lg-3"></div>
    </div>
  </div>

<% end %>